### ISSUE TITLE
project 2 issue 

### ISSUE THREAD

**Issue by mohamed20163858** [iAmWaris97/AwesomeBooks#3]
your project seems perfect every part of it is just a matter of piece excellent work! however, we have some optional opinions:-
1) we think it is better to check the title and author field using javascript to enable you to send your own messages instead of using required in HTML 
2) we think it is better to use <button> tag instead of <a> for button 
3) we think to try to add event listener to each button will be better rather than add event listener for one form

**Comment by iAmWaris97** [comment]
Thank you for the kind review and comments.
I appreciate your time and I went through the issue you raised and the comments. And I think they are great comments to improve my project quality.
While I made some of the requested changes I am working to apply all those changes.
